# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 16:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('short_name', models.CharField(max_length=200)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('category', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('url', models.URLField(max_length=500)),
                ('country', models.CharField(max_length=300)),
                ('town', models.CharField(max_length=200)),
                ('information', models.TextField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('abstract', models.TextField(max_length=5000)),
                ('length', models.DurationField()),
                ('date', models.DateField(verbose_name='Presentation Date')),
                ('category', models.CharField(max_length=200)),
                ('group', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('information', models.TextField(max_length=5000)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Conference')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=200)),
                ('information', models.CharField(max_length=6000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='presentation',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.UserProfile'),
        ),
        migrations.AddField(
            model_name='conference',
            name='coordinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.UserProfile'),
        ),
    ]
