# Generated by Django 2.2.1 on 2019-06-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20190530_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='information',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='conference',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='conference',
            name='status',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='abstract',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='information',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='status',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='information',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.TextField(),
        ),
    ]
