# Generated by Django 2.2.1 on 2019-06-05 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20190605_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='length',
        ),
    ]
