# Generated by Django 2.2.1 on 2019-08-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_userprofile_new_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='new_field',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='message_from_admin',
            field=models.TextField(null=True),
        ),
    ]
