# Generated by Django 2.2.1 on 2019-08-08 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_usermessages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='message_from_admin',
        ),
    ]
