# Generated by Django 2.2.1 on 2019-08-08 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_remove_userprofile_message_from_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMessages',
            new_name='UserMessage',
        ),
    ]
