# Generated by Django 2.2.1 on 2020-01-29 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20190808_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='assistants',
            field=models.ManyToManyField(related_name='user_conferences', through='database.ConferenceAssistance', to='database.UserProfile'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='presentation_file',
            field=models.FileField(default='sample', upload_to=''),
            preserve_default=False,
        ),
    ]
