# Generated by Django 2.2.1 on 2020-02-18 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20200129_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='state',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved')], default='pending', max_length=20),
        ),
    ]
