# Generated by Django 2.2.5 on 2021-04-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_presentation_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_login',
            field=models.DateTimeField(
                blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(
                default='passw', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
