# Generated by Django 2.2.5 on 2021-04-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0018_auto_20210418_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='presentation_file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
